### ISSUE TITLE
Will not run using nodeman

### ISSUE THREAD

**Issue by stunjiturner** [moltin-examples/graphql-moltin-server#5]
Error: Cannot find module 'typescript'

**Comment by notrab** [comment]
Hey @stunjiturner

Are you using `yarn dev` to start the server or using `nodemon` directly?

**Comment by stunjiturner** [comment]
Yarn Dev

S Tunji Turner
sightuary
@sightuary

**Comment by stunjiturner** [comment]
@notrab anything you think I am missing
