### ISSUE TITLE
Typescript Error 

### ISSUE THREAD

**Issue by stunjiturner** [moltin-examples/graphql-moltin-server#6]
`const brandLoader = new DataLoader(async brandIds => {
  return brandIds.map(async id => {
    const { data } = await Moltin.Brands.Get(id)

    return data
  })
})`

src/loaders/index.ts(8,46): error TS2345: Argument of type '{}' is not assignable to parameter of type 'string'. 

I updated all dependencies just to get it to build properly, below is my package.json

``` {
  "name": "moltinql",
  "private": true,
  "version": "0.0.3",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "dev": "npm-run-all --parallel dev:server playground",
    "dev:server": "nodemon -e ts,graphql -x ts-node -r dotenv/config src",
    "playground": "graphql playground",
    "deploy": "now --public --dotenv .env.production && now alias && now rm --yes --safe moltinql",
    "build": "rimraf dist && tsc",
    "start": "node dist"
  },
  "dependencies": {
    "@moltin/sdk": "^3.3.0",
    "dataloader": "^1.4.0",
    "graphql-yoga": "^1.4.3",
    "node-fetch": "^2.0.0"
  },
  "devDependencies": {
    "@types/node": "^10.12.12",
    "@types/node-fetch": "^2.1.4",
    "dotenv": "^6.2.0",
    "graphql-cli": "^2.15.7",
    "nodemon": "^1.15.1",
    "now": "^12.1.9",
    "npm-run-all": "^4.1.5",
    "rimraf": "^2.6.2",
    "ts-node": "^7.0.1",
    "typescript": "^3.2.2"
  },
  "now": {
    "alias": "moltinql"
  },
  "prettier": {
    "semi": false,
    "singleQuote": true,
    "trailingComma": "all"
  },
  "engines": {
    "node": "<= 8"
  }
}
```

**Comment by stunjiturner** [comment]
any help with issue?

**Comment by ynnoj** [comment]
@stunjiturner Can you share the query you're running that is throwing the error?

**Comment by stunjiturner** [comment]
I am attemptting to load the brands, nothing different than the original repo code.

```   brands: async (parent, args, { Moltin }) => {
    try {
      const { data: brands } = await Moltin.Brands.All()

      return brands
    } catch (e) {
      return e
    }
  },

  brand: async (parent, { id }, { Moltin }) => {
    try {
      const { data: brand } = await Moltin.Brands.Get(id)

      return brand
    } catch (e) {
      return e
    }
  },
}
```

**Comment by ynnoj** [comment]
I can't really help you debug this without seeing more of the source. Can you share the repo?

**Comment by stunjiturner** [comment]
I am using the same repo, no changes except removal of the keyBy

**Comment by stunjiturner** [comment]
Can you get a successful build with the master repo?

**Comment by ynnoj** [comment]
Yeah, I can run the app fine located here.

> src/loaders/index.ts(8,46): error TS2345: Argument of type '{}' is not assignable to parameter of type 'string'.

Is that the error you're seeing?

**Comment by stunjiturner** [comment]
yes

**Comment by ynnoj** [comment]
> yes, is there a fix on the way.

I'm not really sure there's a fix in this instance - it builds and runs locally ok here using our demo store data. As the error suggests it looks as though you're passing an incorrect type as an argument somewhere.

This repository is purely for demonstration purposes - how one _could_ build a GraphQL aggregation around the Moltin REST API. We don't really maintain this or suggest using it in production.

**Comment by ynnoj** [comment]
@stunjiturner I'd recommend cloning **this** repository locally add your store `client_id` and see if it builds 👍

**Comment by stunjiturner** [comment]
that's when I get the error.
