### ISSUE TITLE
Typescript Compiler Error, keyBy

### ISSUE THREAD

**Issue by stunjiturner** [moltin-examples/graphql-moltin-server#7]
when using import

``` 
import { keyBy } from 'lodash'
```

TSError: ⨯ Unable to compile TypeScript:
src/loaders/index.ts(2,1): error TS6133: 'keyBy' is declared but its value is never read.

**Comment by ynnoj** [comment]
@stunjiturner It looks as thought you're **not** using `keyBy` in your code? If that's the case then don't import it, otherwise TypeScript will fail co compile as you're seeing 🙃

**Comment by stunjiturner** [comment]
Yeah I removed it, the original repo has it in the code. Why does the brand query fail, issue #1
